theme: main
paginate: 50
preserveTaxonomyNames: true
disableKinds: ["RSS"]
enableRobotsTXT: true
themesDir: themes
summaryLength: 10
DefaultContentLanguage: it
baseURL: /
#defaultContentLanguageInSubdir: true


taxonomies:
  tag: tags

languages:
  it:
    #    baseURL: https://example1.com/
    title: searchworkd.pro - SEO, ricerca notizie di marketing ed esercitazioni
    menu_title: searchworkd.pro
    description: searchworld.pro è dedicato alla produzione delle ultime notizie di ricerca, le migliori guide e how-to per la comunità SEO e marketer.
    languageCode: it-IT
    lang_name: Italiano
  de:
    #    baseURL: https://example2.com/
    title: searchworkd.pro - SEO, Suche nach Marketingnachrichten und Tutorials
    menu_title: searchworkd.pro
    languageCode: de-DE
    lang_name: Deutsch
    description: searchworld.pro ist bestrebt, die neuesten Suchnachrichten, die besten Leitfäden und Anleitungen für die SEO- und Marketer-Community zu produzieren.

params:
  title: klubzdrowia.icu
  subtitle: Informacje medyczne i porady zdrowotne, którym możesz zaufać.
  description: Zależy nam na tym, aby być źródłem specjalistycznych wskazówek zdrowotnych. Przyjdź do nas w swoim dążeniu do odnowy biologicznej.
  metaDescription: Zależy nam na tym, aby być źródłem specjalistycznych wskazówek zdrowotnych. Przyjdź do nas w swoim dążeniu do odnowy biologicznej.
  pageNotFoundTitle: 404 - Page not found
  cse: 002181638325239780683:wuepawcebtk
  gtm: GTM-WKSJDTD
  static_domain_prefix: /
  homepage_publish_date: true
  newsletter:
    show: false
  single_page:
    partial: content
  ads:
    top_ad:
      partial: dynamic
      location: top
    bottom_ad:
      partial: dynamic
      location: bottom
    side_ad:
      partial: dynamic
      location: side
    above_content_ad:
      partial: dynamic
      location: above_content
    below_content_ad:
      partial: dynamic
      location: below_content
    in_post:
      partial: dynamic
      location: in_post
    related_articles:
      partial: dynamic
      location: related
  css_theme: regular
  sitemap:
    changefreq: monthly
  header_partials:
    - partial: amazon-buy-button-header
  body_partials:
    - partial: amazon-buy-button
      text: Buy now
  after_content_partials:
    - partial: amazon-related-products

  multilang:
    share_sitemap_index: true
