baseurl: https://celebrity-hair-secrets.com/
theme: main
languageCode: en-US
paginate: 71
preserveTaxonomyNames: true
title: nude-famous-people.com | All celebs - all the time
disableKinds: ["RSS"]
enableRobotsTXT: true
themesDir: themes
summaryLength: 10

params:
  title: nfp.com
  subtitle: All celebs - all the time.
  description: Find all the celeb nude photoes you will ever need, unique photos gathered from around the web for your delight, sexy and bold celebs.
  pageNotFoundTitle: 404 - Page not found
  cse: 002181638325239780683:wuepawcebtk
  gtm: GTM-PQPN62S
  static_domain_prefix: https://nude-famous-people-com.all-assets.xyz/
  single_page:
    partial: nfp.com
  ads:
    top_ad:
      partial: morenitch
      banner_image_url: https://eu1-us1.ckcdnassets.com/1298/creatives/5354/blackwolf-generic-728x90.png
      banner_url: https://mixi.mn/?a=146186&c=5198&p=r&s3=top-banner
    bottom_ad:
      partial: morenitch
      banner_image_url: https://eu1-us1.ckcdnassets.com/1298/creatives/5778/WeightLoss5.jpg
      banner_url: https://mixi.mn/?a=146186&c=30&p=r&s2=bottom-banner
    side_ad:
      partial: morenitch
      banner_image_url: https://eu1-us1.ckcdnassets.com/1298/creatives/6195/Forskolin250_english_300x300.jpg
      banner_url: https://mixi.mn/?a=146186&c=6186&p=r&s2=side-banner
  homepage_publish_date: false
  sitemap:
    changefreq: monthly
  sections:
    first_title: More celeb nude photoes
    second_title: Even more nude celeb photos for everyone
