theme: main
paginate: 50
preserveTaxonomyNames: true
disableKinds: ["RSS"]
enableRobotsTXT: true
themesDir: themes
summaryLength: 10
DefaultContentLanguage: it
#defaultContentLanguageInSubdir: true


taxonomies:
  tag: tags

languages:
  it:
    baseURL: https://example1.com/
    title: searchworkd.pro - SEO, ricerca notizie di marketing ed esercitazioni
    menu_title: searchworkd.pro
    description: searchworld.pro è dedicato alla produzione delle ultime notizie di ricerca, le migliori guide e how-to per la comunità SEO e marketer.
    languageCode: it-IT
    lang_name: Italiano
  de:
    baseURL: https://example2.com/
    title: searchworkd.pro - SEO, Suche nach Marketingnachrichten und Tutorials
    menu_title: searchworkd.pro
    languageCode: de-DE
    lang_name: Deutsch
    description: searchworld.pro ist bestrebt, die neuesten Suchnachrichten, die besten Leitfäden und Anleitungen für die SEO- und Marketer-Community zu produzieren.
  es:
    baseURL: https://example3.com/
    title: searchworkd.pro - SEO, búsqueda de noticias de marketing y tutoriales.
    menu_title: searchworkd.pro
    languageCode: es-ES
    lang_name: español
    description: searchworld.pro está dedicado a producir las últimas noticias de búsqueda, las mejores guías y procedimientos para la comunidad de SEO y marketing.
  fr:
    baseURL: https://example4.com/
    title: searchworkd.pro - SEO, actualités et tutoriels de marketing de recherche
    menu_title: searchworkd.pro
    languageCode: fr-FR
    lang_name: français
    description: searchworld.pro se consacre à la production des dernières nouvelles en matière de recherche, des meilleurs guides et des guides pour la communauté des spécialistes du marketing et du référencement.

params:
  title: klubzdrowia.icu
  subtitle: Informacje medyczne i porady zdrowotne, którym możesz zaufać.
  description: Zależy nam na tym, aby być źródłem specjalistycznych wskazówek zdrowotnych. Przyjdź do nas w swoim dążeniu do odnowy biologicznej.
  metaDescription: Zależy nam na tym, aby być źródłem specjalistycznych wskazówek zdrowotnych. Przyjdź do nas w swoim dążeniu do odnowy biologicznej.
  pageNotFoundTitle: 404 - Page not found
  cse: 002181638325239780683:wuepawcebtk
  gtm: GTM-PQPN62S
  static_domain_prefix: /
  newsletter:
    show: false
  single_page:
    partial: content
  ads:
    top_ad:
      partial: morenitch
      banner_image_url: https://eu1-us1.ckcdnassets.com/1298/creatives/5354/blackwolf-generic-728x90.png
      banner_url: https://mixi.mn/?a=146186&c=5198&p=r&s3=top-banner
    bottom_ad:
      partial: morenitch
      banner_image_url: https://eu1-us1.ckcdnassets.com/1298/creatives/5778/WeightLoss5.jpg
      banner_url: https://mixi.mn/?a=146186&c=30&p=r&s2=bottom-banner
    side_ad:
      partial: morenitch
      banner_image_url: https://eu1-us1.ckcdnassets.com/1298/creatives/6195/Forskolin250_english_300x300.jpg
      banner_url: https://mixi.mn/?a=146186&c=6186&p=r&s2=side-banner
  css_theme: regular
  sitemap:
    changefreq: monthly
  in_post_ad:
    pub_id: ca-pub-3609124934128625
    slot_id: 4432820139
  multilang:
    share_sitemap_index: true
